name: onlyproject
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  local_auth_android: ^2.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  flutter_screenutil: ^5.9.3
  adaptive_dialog: ^2.6.0
  intl: ^0.20.2
  equatable: ^2.0.8
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logoapp.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/translations/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inder_Regular.ttf
